# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "http://cloud.github.io" # the subpath of your site, e.g. /blog/
url: "https://cloud.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
